# Generated by Django 5.2.7 on 2025-10-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheetupload',
            name='file_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='aadhaar_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='community_certificate_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='hsc_marksheet_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='semester_marksheet_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='signature_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='sslc_marksheet_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='transfer_certificate_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='ug_marksheet_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
