# Generated by Django 5.2.7 on 2025-10-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_marksheetupload_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=236.0, max_digits=10),
        ),
    ]
