# Generated by Django 5.2.7 on 2025-11-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_courses_application_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lsc_code',
            field=models.CharField(blank=True, help_text='LSC Center Code', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lsc_name',
            field=models.CharField(blank=True, help_text='LSC Center Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='referral_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when student signed up via LSC', null=True),
        ),
    ]
