# Generated by Django 5.2.7 on 2025-11-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_lsc_code_student_lsc_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.CharField(blank=True, help_text='Format: PU/MODE/LSC_CODE/YEAR/NUMBER', max_length=100, null=True, unique=True),
        ),
    ]
