# Generated by Django 4.2.16 on 2025-12-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_application_missing_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllCourses',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='application',
            name='admission_confirmed',
            field=models.BooleanField(default=False, help_text='Whether admission has been confirmed'),
        ),
        migrations.AddField(
            model_name='application',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='document_validation',
            field=models.JSONField(blank=True, help_text='Stores document validation status', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='eligibility_status',
            field=models.CharField(blank=True, help_text='Eligibility status: Eligible, Not Eligible, Pending', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='eligibility_verified',
            field=models.BooleanField(default=False, help_text='Whether eligibility has been verified'),
        ),
        migrations.AddField(
            model_name='application',
            name='enrollment_no',
            field=models.CharField(blank=True, help_text='Generated enrollment number (e.g., A25PBA21010001)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if not confirmed', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='verification_remarks',
            field=models.TextField(blank=True, help_text='Remarks for eligibility verification', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='verified_by',
            field=models.CharField(blank=True, help_text='Name/ID of person who verified', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='verified_date',
            field=models.DateTimeField(blank=True, help_text='Date when verification was completed', null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='code2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='degree',
            field=models.CharField(max_length=100),
        ),
    ]
