# Generated by Django 4.2.16 on 2025-12-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_allcourses_remove_courses_created_at_and_more'),
    ]

    operations = [
    ]
