# Generated by Django 4.2.16 on 2025-12-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20251206_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admission_confirmed',
            field=models.BooleanField(default=False, help_text='Whether admission has been confirmed'),
        ),
        migrations.AddField(
            model_name='application',
            name='eligibility_status',
            field=models.CharField(blank=True, help_text='Eligibility status: Eligible, Not Eligible, Pending', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='eligibility_verified',
            field=models.BooleanField(default=False, help_text='Whether eligibility has been verified'),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if not confirmed', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='verification_remarks',
            field=models.TextField(blank=True, help_text='Remarks for eligibility verification', null=True),
        ),
    ]
