# Generated by Django 4.2.16 on 2025-12-07 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_add_eligibility_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(blank=True, max_length=100, null=True)),
                ('student_email', models.EmailField(max_length=191)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('semester', models.CharField(max_length=20)),
                ('semester_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(default='Credit/Debit Card', max_length=50)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('card_last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('payment_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'semester_payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['user', 'semester_number'], name='semester_pa_user_id_9fc176_idx'), models.Index(fields=['student_email', 'payment_status'], name='semester_pa_student_5d44f1_idx'), models.Index(fields=['transaction_id'], name='semester_pa_transac_5b7b17_idx')],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the material', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the material', null=True)),
                ('material_type', models.CharField(choices=[('PDF', 'PDF Document'), ('PPT', 'PowerPoint Presentation')], default='PDF', max_length=10)),
                ('file', models.FileField(help_text='Upload PDF or PPT file (Max 30MB)', max_length=500, upload_to='materials/%Y/%m/')),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('programme', models.CharField(help_text='Target programme (e.g., BBA, MBA)', max_length=100)),
                ('semester', models.IntegerField(help_text='Target semester (1-6)')),
                ('subject', models.CharField(blank=True, help_text='Subject name', max_length=200, null=True)),
                ('lsc_code', models.CharField(help_text='LSC Center Code', max_length=50)),
                ('lsc_name', models.CharField(help_text='LSC Center Name', max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('views_count', models.IntegerField(default=0, help_text='Number of times viewed')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'materials',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['lsc_code', 'programme', 'semester'], name='materials_lsc_cod_1d0c25_idx'), models.Index(fields=['status', 'upload_date'], name='materials_status_c80b0d_idx')],
            },
        ),
    ]
