# Generated by Django 4.2.16 on 2025-12-08 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_material_uploaded_by_name_alter_material_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='uploaded_by_name',
            field=models.CharField(blank=True, help_text='Name of uploader', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
