# Generated by Django 4.2.16 on 2025-12-08 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_material_uploaded_by_name_alter_material_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_views', to='api.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'material_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['material', 'user'], name='material_vi_materia_d8a5cd_idx'), models.Index(fields=['viewed_at'], name='material_vi_viewed__4cd1aa_idx')],
                'unique_together': {('material', 'user')},
            },
        ),
    ]
