# Generated by Django 4.2.16 on 2025-12-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20251208_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=254)),
                ('lsc_code', models.CharField(help_text='LSC Center Code', max_length=50)),
                ('category', models.CharField(choices=[('COURSE_CONTENT', 'Course Content'), ('PORTAL_EXPERIENCE', 'Portal Experience'), ('SUPPORT', 'Support Services'), ('LSC_EXPERIENCE', 'LSC Center Experience'), ('GENERAL', 'General Feedback')], default='GENERAL', max_length=50)),
                ('rating', models.IntegerField(choices=[(1, '1 Star - Poor'), (2, '2 Stars - Fair'), (3, '3 Stars - Good'), (4, '4 Stars - Very Good'), (5, '5 Stars - Excellent')], help_text='Rating out of 5')),
                ('title', models.CharField(help_text='Feedback title/subject', max_length=200)),
                ('message', models.TextField(help_text='Detailed feedback message')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('FLAGGED', 'Flagged'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('is_flagged', models.BooleanField(default=False, help_text='Flag for priority review')),
                ('admin_notes', models.TextField(blank=True, help_text="Admin's internal notes", null=True)),
                ('reviewed_by', models.CharField(blank=True, help_text='Admin who reviewed', max_length=200, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Review timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feedbacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lsc_code', 'status'], name='feedbacks_lsc_cod_80ca51_idx'), models.Index(fields=['rating', 'created_at'], name='feedbacks_rating_efe1c7_idx'), models.Index(fields=['is_flagged', 'status'], name='feedbacks_is_flag_b5ad1a_idx')],
            },
        ),
    ]
