# Generated by Django 5.2.7 on 2025-11-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_applicationsettings_systemsettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationsettings',
            options={'ordering': ['-admission_year', '-opening_date'], 'verbose_name': 'Application Setting', 'verbose_name_plural': 'Application Settings'},
        ),
        migrations.RemoveField(
            model_name='applicationsettings',
            name='application_type',
        ),
        migrations.RemoveField(
            model_name='applicationsettings',
            name='is_open',
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='admission_code',
            field=models.CharField(blank=True, help_text='Admission Code (Ex: A24)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='admission_key',
            field=models.CharField(blank=True, help_text='Unique admission key for reference', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='admission_type',
            field=models.CharField(blank=True, choices=[('ACADEMIC_YEAR', 'Academic Year'), ('CALENDAR_YEAR', 'Calendar Year'), ('UG', 'Under Graduate'), ('PG', 'Post Graduate'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE', 'Certificate'), ('PHD', 'PhD'), ('DISTANCE', 'Distance Education'), ('ONLINE', 'Online Program')], help_text='Type of admission program', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='admission_year',
            field=models.CharField(blank=True, help_text='Academic year (Ex: 2024-25 or 2025)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('SCHEDULED', 'Scheduled'), ('EXPIRED', 'Expired')], default='CLOSED', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='closing_date',
            field=models.DateField(blank=True, help_text='Date when online application closes', null=True),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about this admission session'),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='max_applications',
            field=models.PositiveIntegerField(default=0, help_text='Maximum applications (0 for unlimited)'),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='opening_date',
            field=models.DateField(blank=True, help_text='Date when online application opens', null=True),
        ),
        migrations.AlterModelTable(
            name='applicationsettings',
            table='portal_applicationsettings',
        ),
    ]
