# Generated by Django 5.2.7 on 2025-11-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_applicationsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='is_close',
            field=models.BooleanField(default=True, help_text='Manual override: Is admission currently closed?'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='is_open',
            field=models.BooleanField(default=False, help_text='Manual override: Is admission currently open?'),
        ),
    ]
