# Generated by Django 5.2.7 on 2025-11-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_applicationsettings_is_close_and_more'),
    ]

    operations = [
        # Fix nullable fields by providing defaults and making them non-nullable
        migrations.AlterField(
            model_name='applicationsettings',
            name='admission_code',
            field=models.CharField(help_text='Admission Code (Ex: A24)', max_length=20, unique=True, default='DEFAULT'),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='admission_key',
            field=models.CharField(help_text='Unique admission key for reference', max_length=50, unique=True, default='DEFAULT_KEY'),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='admission_type',
            field=models.CharField(choices=[('ACADEMIC_YEAR', 'Academic Year'), ('CALENDAR_YEAR', 'Calendar Year'), ('UG', 'Under Graduate'), ('PG', 'Post Graduate'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE', 'Certificate'), ('PHD', 'PhD'), ('DISTANCE', 'Distance Education'), ('ONLINE', 'Online Program')], help_text='Type of admission program', max_length=50, default='ACADEMIC_YEAR'),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='admission_year',
            field=models.CharField(help_text='Academic year (Ex: 2024-25 or 2025)', max_length=20, default='2024-25'),
        ),
    ]
