# Generated by Django 5.2.7 on 2025-11-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20251102_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsettings',
            name='admission_code',
            field=models.CharField(help_text='Admission Code (Ex: A24)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='admission_key',
            field=models.CharField(help_text='Unique admission key for reference', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='admission_type',
            field=models.CharField(choices=[('ACADEMIC_YEAR', 'Academic Year'), ('CALENDAR_YEAR', 'Calendar Year'), ('UG', 'Under Graduate'), ('PG', 'Post Graduate'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE', 'Certificate'), ('PHD', 'PhD'), ('DISTANCE', 'Distance Education'), ('ONLINE', 'Online Program')], help_text='Type of admission program', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='admission_year',
            field=models.CharField(help_text='Academic year (Ex: 2024-25 or 2025)', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='is_close',
            field=models.BooleanField(default=True, help_text='Manual override: Force admission to be closed'),
        ),
        migrations.AlterField(
            model_name='applicationsettings',
            name='is_open',
            field=models.BooleanField(default=False, help_text='Manual override: Force admission to be open'),
        ),
    ]
