# Generated by Django 5.2.7 on 2025-11-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsc_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSCAdmin',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('lsc_code', models.CharField(db_column='lsc_code', max_length=50, unique=True)),
                ('center_name', models.CharField(db_column='center_name', max_length=200)),
                ('admin_email', models.EmailField(db_column='admin_email', max_length=254)),
                ('admin_password', models.CharField(db_column='admin_password', max_length=256)),
                ('admin_name', models.CharField(db_column='admin_name', max_length=100)),
                ('mobile', models.CharField(db_column='mobile', max_length=15)),
                ('address', models.TextField(db_column='address')),
                ('district', models.CharField(db_column='district', max_length=100)),
                ('state', models.CharField(db_column='state', max_length=100)),
                ('pincode', models.CharField(db_column='pincode', max_length=10)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('created_by', models.CharField(db_column='created_by', max_length=254)),
            ],
            options={
                'db_table': 'lsc_admins',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='lscuser',
            table='lsc_auth_lscuser',
        ),
    ]
