# Generated by Django 5.2.7 on 2025-11-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsc_auth', '0002_lscadmin_alter_lscuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='lscuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lscuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
