# Generated by Django 5.2.7 on 2025-11-02 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_code', models.CharField(help_text='Admission Code (Ex: A24)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Only uppercase letters and numbers allowed', regex='^[A-Z0-9]+$')])),
                ('admission_type', models.CharField(choices=[('UG', 'Under Graduate'), ('PG', 'Post Graduate'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE', 'Certificate'), ('PHD', 'PhD'), ('DISTANCE', 'Distance Education'), ('ONLINE', 'Online Program')], help_text='Type of admission program', max_length=50)),
                ('admission_year', models.CharField(help_text='Academic year (Ex: 2024-25 or 2025)', max_length=20, validators=[django.core.validators.RegexValidator(message='Format: YYYY or YYYY-YY', regex='^\\d{4}(-\\d{2})?$')])),
                ('admission_key', models.CharField(help_text='Unique admission key for reference', max_length=50, unique=True)),
                ('opening_date', models.DateField(help_text='Date when online application opens')),
                ('closing_date', models.DateField(help_text='Date when online application closes')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('SCHEDULED', 'Scheduled'), ('EXPIRED', 'Expired')], default='CLOSED', help_text='Current admission status', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about this admission session', null=True)),
                ('max_applications', models.IntegerField(default=0, help_text='Maximum number of applications allowed (0 for unlimited)')),
                ('current_applications', models.IntegerField(default=0, help_text='Current number of applications received')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admission Session',
                'verbose_name_plural': 'Admission Sessions',
                'db_table': 'admission_sessions',
                'ordering': ['-admission_year', '-opening_date'],
            },
        ),
    ]
