# Generated by Django 5.2.7 on 2025-11-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionsession',
            name='admission_type',
            field=models.CharField(choices=[('UG', 'Under Graduate'), ('PG', 'Post Graduate'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE', 'Certificate'), ('PHD', 'PhD'), ('DISTANCE', 'Distance Education'), ('ONLINE', 'Online Program'), ('ACADEMIC_YEAR', 'Academic Year'), ('CALENDAR_YEAR', 'Calendar Year')], help_text='Type of admission program', max_length=50),
        ),
    ]
